INSERT INTO `FOOD` (`ID`,`TYPE`,`NAME`,`DESCRIPTION`,`PRICE`,`IMAGE_URL`,`ACTIVE`,`FEATURED`) VALUES (1,0,'Суп','Смачний суп',50.50,'images/food/sup-ovocheviy.jpg',1,1);
INSERT INTO `FOOD` (`ID`,`TYPE`,`NAME`,`DESCRIPTION`,`PRICE`,`IMAGE_URL`,`ACTIVE`,`FEATURED`) VALUES (2,0,'Борщ','Український борщ',60.00,'images/food/borsch.jpg',1,1);
INSERT INTO `FOOD` (`ID`,`TYPE`,`NAME`,`DESCRIPTION`,`PRICE`,`IMAGE_URL`,`ACTIVE`,`FEATURED`) VALUES (3,3,'Фруктовий стакан','Фрукти у власному соці',40.00,'images/food/fruits-stakan.jpg',1,1);
INSERT INTO `FOOD` (`ID`,`TYPE`,`NAME`,`DESCRIPTION`,`PRICE`,`IMAGE_URL`,`ACTIVE`,`FEATURED`) VALUES (4,2,'Зелений чай','Тигуанинь Нунсян',30.00,'images/food/tea-green.jpg',1,0);
INSERT INTO `FOOD` (`ID`,`TYPE`,`NAME`,`DESCRIPTION`,`PRICE`,`IMAGE_URL`,`ACTIVE`,`FEATURED`) VALUES (5,2,'Апельсиновий фреш','Свіжий апельсиновий фреш',35.00,'images/food/apelsin-juise.jpg',1,1);
INSERT INTO `FOOD` (`ID`,`TYPE`,`NAME`,`DESCRIPTION`,`PRICE`,`IMAGE_URL`,`ACTIVE`,`FEATURED`) VALUES (6,2,'Чорний чай','Чорний чай',35.00,'images/food/tea-black.jpg',1,1);
INSERT INTO `FOOD` (`ID`,`TYPE`,`NAME`,`DESCRIPTION`,`PRICE`,`IMAGE_URL`,`ACTIVE`,`FEATURED`) VALUES (7,1,'Овочевий салат','Овочефий салат з сиром фета',30.00,'images/food/salat-2.jpg',1,0);
INSERT INTO `FOOD` (`ID`,`TYPE`,`NAME`,`DESCRIPTION`,`PRICE`,`IMAGE_URL`,`ACTIVE`,`FEATURED`) VALUES (8,1,'Чапаті','Пісний хліб чапаті',20.00,'images/food/chapati.jpg',1,0);
INSERT INTO `FOOD` (`ID`,`TYPE`,`NAME`,`DESCRIPTION`,`PRICE`,`IMAGE_URL`,`ACTIVE`,`FEATURED`) VALUES (9,3,'Фруктовий салат','Соковитий фруктовий салат',45.00,'images/food/fruit-salad-2.jpg',1,1);
INSERT INTO `FOOD` (`ID`,`TYPE`,`NAME`,`DESCRIPTION`,`PRICE`,`IMAGE_URL`,`ACTIVE`,`FEATURED`) VALUES (10,1,'Картопля з овочами','Смажена картопля в овочевому салаті',50.00,'images/food/food-1.jpg',1,0);
INSERT INTO `FOOD` (`ID`,`TYPE`,`NAME`,`DESCRIPTION`,`PRICE`,`IMAGE_URL`,`ACTIVE`,`FEATURED`) VALUES (11,3,'Фруктова нарізка','Салат з фруктів',50.00,'images/food/fruit-salad.jpg',1,0);
INSERT INTO `FOOD` (`ID`,`TYPE`,`NAME`,`DESCRIPTION`,`PRICE`,`IMAGE_URL`,`ACTIVE`,`FEATURED`) VALUES (12,3,'Фруктовий десерт','Десерт на основі фруктів і солодкої квасолі',55.00,'images/food/salat-1.jpg',1,0);
